### ISSUE TITLE
What is the best format for .jbuild.project to manage the project

### ISSUE THREAD

**Issue by FauconFan** [FauconFan/jbuild#7]
HELP.

**Comment by Peaupote** [comment]
A json or a yaml like this

```yaml
name: MyProject
description: lorem
author: FauconFan

require:
  - lib-ocr:
    src: /path/to/the/sources
    version: 0.5

require-dev:
  - junit
    src: /path/to/source

src:
  - fr
    - fauconfan
      - package1
        - Main
          description: Main class of the project
          - public:
            - x
              type: int
              description: The x number
              final: true
         - private:
           - y
             type: boolean
             description: A boolean variable

# etc..
```
